development:
  adapter: postgresql
  database: level_revel_development
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres
test:
  adapter: postgresql
  database: level_revel_test
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  password: postgres
production:
  adapter: postgresql
  database: level_revel_production
  pool: 5
  timeout: 5000
